version: '3.4'

services:
  dist:
    image: dist
    build:
      context: node_modules/terser/dist
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3080:3080
