version: '3.4'

services:
  dist:
    image: dist
    build:
      context: node_modules/terser/dist
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3080:3080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "bundle.min.js"]
